//! Emulation of Python's `str % args` and `str.format(*args, **kwargs)` for
//! the dummy arguments the PO checks use (`''` for `%s`, `0` otherwise), with
//! CPython's exception types and messages.
//!
//! Verified against CPython by `tests/data/pyformat_cases.json`, generated by
//! `scripts/gen_pyformat_cases.py`.

use crate::pyliteral::repr_str;
use std::collections::BTreeMap;

/// A dummy value: what the PO checks pass for each placeholder.
#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    /// `''`
    Str,
    Int(i64),
    /// The kwargs dict itself, used as a single positional argument.
    Dict,
}

impl Value {
    fn type_name(&self) -> &'static str {
        match self {
            Value::Str => "str",
            Value::Int(_) => "int",
            Value::Dict => "dict",
        }
    }

    fn is_number(&self) -> bool {
        matches!(self, Value::Int(_))
    }
}

/// Arguments of a `%` operation: a tuple, or a dict for `%(name)s`.
#[derive(Debug, Clone, PartialEq)]
pub enum PercentArgs {
    Tuple(Vec<Value>),
    Dict(BTreeMap<String, Value>),
}

/// A Python exception, rendered as `repr(exc)`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PyError {
    pub kind: &'static str,
    pub message: String,
}

impl PyError {
    fn new(kind: &'static str, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
        }
    }

    /// `repr(exc)`, e.g. `TypeError('not enough arguments for format string')`.
    pub fn repr(&self) -> String {
        format!("{}({})", self.kind, repr_str(&self.message))
    }
}

/// `format % args`, returning the exception Python would raise, if any.
pub fn percent_format(format: &str, args: &PercentArgs) -> Result<(), PyError> {
    let chars: Vec<char> = format.chars().collect();
    let (tuple, dict) = match args {
        PercentArgs::Tuple(values) => (Some(values.as_slice()), None),
        PercentArgs::Dict(map) => (None, Some(map)),
    };
    // A dict is also a single positional argument (`'%s' % {}` works).
    let arglen: isize = tuple.map_or(-1, |t| t.len() as isize);
    let mut argidx: isize = 0;
    let mut used_single = false;

    let mut next_arg = |argidx: &mut isize| -> Result<Value, PyError> {
        match tuple {
            Some(values) => {
                if *argidx < arglen {
                    *argidx += 1;
                    Ok(values[(*argidx - 1) as usize].clone())
                } else {
                    Err(PyError::new("TypeError", "not enough arguments for format string"))
                }
            }
            None => {
                if *argidx == 0 && !used_single {
                    used_single = true;
                    *argidx = -2;
                    // The dict itself; only `%s`/`%r`/`%a` accept it.
                    Ok(Value::Dict)
                } else {
                    Err(PyError::new("TypeError", "not enough arguments for format string"))
                }
            }
        }
    };

    let mut i = 0;
    while i < chars.len() {
        if chars[i] != '%' {
            i += 1;
            continue;
        }
        i += 1;
        // Only `%%` is an escape; `%5%` is a conversion that takes an argument.
        let directly_after_percent = i;
        let mut keyed: Option<Value> = None;
        if chars.get(i) == Some(&'(') {
            let Some(map) = dict else {
                return Err(PyError::new("TypeError", "format requires a mapping"));
            };
            let mut depth = 1;
            i += 1;
            let start = i;
            while i < chars.len() && depth > 0 {
                match chars[i] {
                    '(' => depth += 1,
                    ')' => depth -= 1,
                    _ => {}
                }
                i += 1;
            }
            if depth > 0 {
                return Err(PyError::new("ValueError", "incomplete format key"));
            }
            let key: String = chars[start..i - 1].iter().collect();
            match map.get(&key) {
                Some(value) => keyed = Some(value.clone()),
                None => return Err(PyError::new("KeyError", key)),
            }
            argidx = -2;
        }
        while i < chars.len() && "-+ #0".contains(chars[i]) {
            i += 1;
        }
        if chars.get(i) == Some(&'*') {
            let width = next_arg(&mut argidx)?;
            if !matches!(width, Value::Int(_)) {
                return Err(PyError::new("TypeError", "* wants int"));
            }
            i += 1;
        } else {
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        }
        if chars.get(i) == Some(&'.') {
            i += 1;
            if chars.get(i) == Some(&'*') {
                let precision = next_arg(&mut argidx)?;
                if !matches!(precision, Value::Int(_)) {
                    return Err(PyError::new("TypeError", "* wants int"));
                }
                i += 1;
            } else {
                while i < chars.len() && chars[i].is_ascii_digit() {
                    i += 1;
                }
            }
        }
        while i < chars.len() && "hlL".contains(chars[i]) {
            i += 1;
        }
        let Some(&conversion) = chars.get(i) else {
            return Err(PyError::new("ValueError", "incomplete format"));
        };
        if conversion == '%' && i == directly_after_percent {
            i += 1;
            continue;
        }
        let value = match keyed {
            Some(value) => value,
            None => next_arg(&mut argidx)?,
        };
        match conversion {
            's' | 'r' | 'a' => {}
            'd' | 'i' | 'u' if !value.is_number() => {
                return Err(PyError::new(
                    "TypeError",
                    format!(
                        "%{conversion} format: a real number is required, not {}",
                        value.type_name()
                    ),
                ));
            }
            'o' | 'x' | 'X' if !value.is_number() => {
                return Err(PyError::new(
                    "TypeError",
                    format!(
                        "%{conversion} format: an integer is required, not {}",
                        value.type_name()
                    ),
                ));
            }
            'e' | 'E' | 'f' | 'F' | 'g' | 'G' if !value.is_number() => {
                return Err(PyError::new(
                    "TypeError",
                    format!("must be real number, not {}", value.type_name()),
                ));
            }
            'c' if value == Value::Str => {
                return Err(PyError::new(
                    "TypeError",
                    "%c requires an int or a unicode character, not a string of length 0",
                ));
            }
            'c' if value == Value::Dict => {
                return Err(PyError::new(
                    "TypeError",
                    "%c requires an int or a unicode character, not dict",
                ));
            }
            'd' | 'i' | 'u' | 'o' | 'x' | 'X' | 'e' | 'E' | 'f' | 'F' | 'g' | 'G' | 'c' => {}
            other => {
                return Err(PyError::new(
                    "ValueError",
                    format!(
                        "unsupported format character '{other}' ({:#x}) at index {i}",
                        other as u32
                    ),
                ));
            }
        }
        i += 1;
    }
    if tuple.is_some() && argidx < arglen && argidx >= 0 {
        return Err(PyError::new(
            "TypeError",
            "not all arguments converted during string formatting",
        ));
    }
    Ok(())
}

/// Attributes an `int` has, for `{0.real}` style fields.
const INT_ATTRIBUTES: &[&str] = &[
    "as_integer_ratio",
    "bit_count",
    "bit_length",
    "conjugate",
    "denominator",
    "from_bytes",
    "imag",
    "is_integer",
    "numerator",
    "real",
    "to_bytes",
];

#[derive(PartialEq)]
enum Numbering {
    Unknown,
    Auto,
    Manual,
}

struct FormatState<'a> {
    args: &'a [Value],
    kwargs: &'a BTreeMap<String, Value>,
    numbering: Numbering,
    auto_index: usize,
}

/// What a replacement field evaluates to, as far as we track it.
enum Field {
    Value(Value),
    /// The result of an attribute lookup; its type is not tracked.
    Unknown,
}

impl FormatState<'_> {
    fn lookup(&mut self, field_name: &str) -> Result<Field, PyError> {
        let chars: Vec<char> = field_name.chars().collect();
        let first_end = chars.iter().position(|c| *c == '.' || *c == '[').unwrap_or(chars.len());
        let first: String = chars[..first_end].iter().collect();
        let mut value = if first.is_empty() {
            if self.numbering == Numbering::Manual {
                return Err(PyError::new(
                    "ValueError",
                    "cannot switch from manual field specification to automatic field numbering",
                ));
            }
            self.numbering = Numbering::Auto;
            let index = self.auto_index;
            self.auto_index += 1;
            self.positional(index)?
        } else if first.chars().all(|c| c.is_ascii_digit()) {
            if self.numbering == Numbering::Auto {
                return Err(PyError::new(
                    "ValueError",
                    "cannot switch from automatic field numbering to manual field specification",
                ));
            }
            self.numbering = Numbering::Manual;
            let index: usize = first
                .parse()
                .map_err(|_| PyError::new("ValueError", "Too many decimal digits in format string"))?;
            self.positional(index)?
        } else {
            match self.kwargs.get(&first) {
                Some(value) => Field::Value(value.clone()),
                None => return Err(PyError::new("KeyError", first)),
            }
        };
        let mut i = first_end;
        while i < chars.len() {
            match chars[i] {
                '.' => {
                    let start = i + 1;
                    let end = chars[start..]
                        .iter()
                        .position(|c| *c == '.' || *c == '[')
                        .map_or(chars.len(), |p| start + p);
                    let attribute: String = chars[start..end].iter().collect();
                    if attribute.is_empty() {
                        return Err(PyError::new("ValueError", "Empty attribute in format string"));
                    }
                    value = match value {
                        Field::Value(Value::Str) => Field::Unknown,
                        Field::Value(_) if INT_ATTRIBUTES.contains(&attribute.as_str()) => Field::Unknown,
                        Field::Value(v) => {
                            return Err(PyError::new(
                                "AttributeError",
                                format!("'{}' object has no attribute '{attribute}'", v.type_name()),
                            ))
                        }
                        Field::Unknown => Field::Unknown,
                    };
                    i = end;
                }
                '[' => {
                    let Some(close) = chars[i..].iter().position(|c| *c == ']') else {
                        return Err(PyError::new("ValueError", "Missing ']' in format string"));
                    };
                    if let Field::Value(Value::Int(_)) = value {
                        return Err(PyError::new("TypeError", "'int' object is not subscriptable"));
                    }
                    value = Field::Unknown;
                    i += close + 1;
                    if i < chars.len() && chars[i] != '.' && chars[i] != '[' {
                        return Err(PyError::new(
                            "ValueError",
                            "Only '.' or '[' may follow ']' in format field specifier",
                        ));
                    }
                }
                _ => break,
            }
        }
        Ok(value)
    }

    fn positional(&self, index: usize) -> Result<Field, PyError> {
        self.args.get(index).cloned().map(Field::Value).ok_or_else(|| {
            PyError::new(
                "IndexError",
                format!("Replacement index {index} out of range for positional args tuple"),
            )
        })
    }
}

/// `format(value, spec)` for the values we track.
/// `format(value, spec)` for the values we track, following CPython's
/// format-spec parser (`parse_internal_render_format_spec`) and the checks of
/// `int.__format__` and `str.__format__`, in the same order.
fn check_spec(value: &Field, spec: &str) -> Result<(), PyError> {
    let Field::Value(value) = value else { return Ok(()) };
    if spec.is_empty() {
        return Ok(());
    }
    let type_name = match value {
        Value::Int(_) => "int",
        Value::Str | Value::Dict => "str",
    };
    let error = |message: String| Err(PyError::new("ValueError", message));
    let chars: Vec<char> = spec.chars().collect();
    let is_align = |c: char| matches!(c, '<' | '>' | '=' | '^');
    let mut pos = 0;
    let mut align = None;
    let mut fill_specified = false;
    if chars.len() >= 2 && is_align(chars[1]) {
        align = Some(chars[1]);
        fill_specified = true;
        pos = 2;
    } else if is_align(chars[0]) {
        align = Some(chars[0]);
        pos = 1;
    }
    let mut sign = false;
    if pos < chars.len() && matches!(chars[pos], '+' | '-' | ' ') {
        sign = true;
        pos += 1;
    }
    let mut no_neg_zero = false;
    if pos < chars.len() && chars[pos] == 'z' {
        no_neg_zero = true;
        pos += 1;
    }
    let mut alternate = false;
    if pos < chars.len() && chars[pos] == '#' {
        alternate = true;
        pos += 1;
    }
    if !fill_specified && pos < chars.len() && chars[pos] == '0' && align.is_none() && type_name == "int" {
        align = Some('=');
    }
    while pos < chars.len() && chars[pos].is_ascii_digit() {
        pos += 1;
    }
    let mut grouping = None;
    if pos < chars.len() && matches!(chars[pos], ',' | '_') {
        grouping = Some(chars[pos]);
        pos += 1;
        if pos < chars.len() && matches!(chars[pos], ',' | '_') {
            return error("Cannot specify both ',' and '_'.".into());
        }
    }
    let mut precision = false;
    if pos < chars.len() && chars[pos] == '.' {
        pos += 1;
        let start = pos;
        while pos < chars.len() && chars[pos].is_ascii_digit() {
            pos += 1;
        }
        if pos == start {
            return error("Format specifier missing precision".into());
        }
        precision = true;
    }
    if chars.len() - pos > 1 {
        return error(format!(
            "Invalid format specifier '{spec}' for object of type '{type_name}'"
        ));
    }
    let format_type = chars.get(pos).copied();
    if let Some(separator) = grouping {
        let allowed = match format_type {
            None | Some('d' | 'e' | 'f' | 'g' | 'E' | 'G' | '%' | 'F') => true,
            Some('b' | 'o' | 'x' | 'X') => separator == '_',
            _ => false,
        };
        if !allowed {
            return error(format!(
                "Cannot specify '{separator}' with '{}'.",
                format_type.unwrap_or(' ')
            ));
        }
    }
    match type_name {
        "int" => match format_type {
            None | Some('b' | 'c' | 'd' | 'o' | 'x' | 'X' | 'n') => {
                if precision {
                    return error("Precision not allowed in integer format specifier".into());
                }
                if no_neg_zero {
                    return error("Negative zero coercion (z) not allowed in integer format specifier".into());
                }
                if format_type == Some('c') && sign {
                    return error("Sign not allowed with integer format specifier 'c'".into());
                }
                if format_type == Some('c') && alternate {
                    return error("Alternate form (#) not allowed with integer format specifier 'c'".into());
                }
                Ok(())
            }
            Some('e' | 'E' | 'f' | 'F' | 'g' | 'G' | '%') => Ok(()),
            Some(other) => error(format!("Unknown format code '{other}' for object of type 'int'")),
        },
        _ => match format_type {
            None | Some('s') => {
                if sign {
                    return error("Sign not allowed in string format specifier".into());
                }
                if no_neg_zero {
                    return error("Negative zero coercion (z) not allowed in string format specifier".into());
                }
                if alternate {
                    return error("Alternate form (#) not allowed in string format specifier".into());
                }
                if align == Some('=') {
                    return error("'=' alignment not allowed in string format specifier".into());
                }
                Ok(())
            }
            Some(other) => error(format!("Unknown format code '{other}' for object of type 'str'")),
        },
    }
}

/// `format.format(*args, **kwargs)`, returning the exception Python would
/// raise, if any.
pub fn str_format(format: &str, args: &[Value], kwargs: &BTreeMap<String, Value>) -> Result<(), PyError> {
    let mut state = FormatState {
        args,
        kwargs,
        numbering: Numbering::Unknown,
        auto_index: 0,
    };
    format_into(format, &mut state, 2)
}

fn format_into(format: &str, state: &mut FormatState, recursion: usize) -> Result<(), PyError> {
    let chars: Vec<char> = format.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        match chars[i] {
            '{' if chars.get(i + 1) == Some(&'{') => i += 2,
            '}' if chars.get(i + 1) == Some(&'}') => i += 2,
            '}' => return Err(PyError::new("ValueError", "Single '}' encountered in format string")),
            '{' => {
                if i + 1 >= chars.len() {
                    return Err(PyError::new("ValueError", "Single '{' encountered in format string"));
                }
                let mut depth = 1;
                let mut j = i + 1;
                while j < chars.len() && depth > 0 {
                    match chars[j] {
                        '{' => depth += 1,
                        '}' => depth -= 1,
                        _ => {}
                    }
                    j += 1;
                }
                if depth > 0 {
                    return Err(PyError::new("ValueError", "expected '}' before end of string"));
                }
                let inner: Vec<char> = chars[i + 1..j - 1].to_vec();
                let mut k = 0;
                let mut in_brackets = false;
                while k < inner.len() {
                    match inner[k] {
                        '[' => in_brackets = true,
                        ']' => in_brackets = false,
                        ':' | '!' if !in_brackets => break,
                        _ => {}
                    }
                    k += 1;
                }
                let name: String = inner[..k].iter().collect();
                let mut rest: &[char] = &inner[k..];
                let mut converted: Option<char> = None;
                if rest.first() == Some(&'!') {
                    let Some(&conversion) = rest.get(1) else {
                        return Err(PyError::new(
                            "ValueError",
                            "end of string while looking for conversion specifier",
                        ));
                    };
                    if rest.len() > 2 && rest[2] != ':' {
                        return Err(PyError::new("ValueError", "expected ':' after conversion specifier"));
                    }
                    converted = Some(conversion);
                    rest = &rest[2..];
                }
                let spec: String = rest.strip_prefix(&[':']).unwrap_or(rest).iter().collect();
                // Python looks the field up before it applies the conversion.
                let value = state.lookup(&name)?;
                if let Some(conversion) = converted.filter(|c| !"rsa".contains(*c)) {
                    return Err(PyError::new(
                        "ValueError",
                        format!("Unknown conversion specifier {conversion}"),
                    ));
                }
                if spec.contains('{') {
                    if recursion == 0 {
                        return Err(PyError::new("ValueError", "Max string recursion exceeded"));
                    }
                    format_into(&spec, state, recursion - 1)?;
                } else {
                    let value = if converted.is_some() {
                        Field::Value(Value::Str)
                    } else {
                        value
                    };
                    check_spec(&value, &spec)?;
                }
                i = j;
            }
            _ => i += 1,
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tuple(values: &[Value]) -> PercentArgs {
        PercentArgs::Tuple(values.to_vec())
    }

    #[test]
    fn percent_errors() {
        let ok = percent_format("%s %d", &tuple(&[Value::Str, Value::Int(0)]));
        assert_eq!(ok, Ok(()));
        let too_many = percent_format("%s", &tuple(&[Value::Str, Value::Int(0)])).unwrap_err();
        assert_eq!(
            too_many.repr(),
            "TypeError('not all arguments converted during string formatting')"
        );
        let wrong_type = percent_format("%d %s", &tuple(&[Value::Str, Value::Int(0)])).unwrap_err();
        assert_eq!(
            wrong_type.repr(),
            "TypeError('%d format: a real number is required, not str')"
        );
        let unsupported = percent_format("%y", &tuple(&[Value::Str])).unwrap_err();
        assert_eq!(
            unsupported.repr(),
            "ValueError(\"unsupported format character 'y' (0x79) at index 1\")"
        );
    }

    #[test]
    fn format_errors() {
        let kwargs = BTreeMap::new();
        let args = [Value::Int(0)];
        assert_eq!(
            str_format("{} {}", &args, &kwargs).unwrap_err().repr(),
            "IndexError('Replacement index 1 out of range for positional args tuple')"
        );
        assert_eq!(
            str_format("{name}", &args, &kwargs).unwrap_err().repr(),
            "KeyError('name')"
        );
        assert_eq!(
            str_format("{0.real} {:d}", &args, &kwargs).unwrap_err().kind,
            "ValueError"
        );
        assert_eq!(str_format("{0:.2f}", &args, &kwargs), Ok(()));
        let spec = |s: &str| check_spec(&Field::Value(Value::Int(0)), s).err().map(|e| e.message);
        assert_eq!(
            spec(" 'value'").as_deref(),
            Some("Invalid format specifier ' 'value'' for object of type 'int'")
        );
        assert_eq!(
            spec(".2d").as_deref(),
            Some("Precision not allowed in integer format specifier")
        );
        assert_eq!(spec(",_d").as_deref(), Some("Cannot specify both ',' and '_'."));
        assert_eq!(spec("x<5"), None);
        let str_spec = |s: &str| check_spec(&Field::Value(Value::Str), s).err().map(|e| e.message);
        assert_eq!(str_spec("05"), None);
        assert_eq!(
            str_spec("=5s").as_deref(),
            Some("'=' alignment not allowed in string format specifier")
        );
    }
}
